### ISSUE TITLE
Not able to execute appium with unicodeKeyboard on Samsung devices

### ISSUE THREAD

**Issue by shibupanda** [appium/io.appium.settings#40]
Appium version: 1.9.1
java client: 7.0.0

Capabilities:
==========
please find the error logs. 
[unicodeKeyboard.txt](https://github.com/appium/io.appium.settings/files/3004117/unicodeKeyboard.txt)

capabilities.setCapability("unicodeKeyboard", true);
capabilities.setCapability("resetKeyboard", true);
capabilities.setCapability("rotatable", true);
capabilities.setCapability("automationName", "uiautomator2");

**Comment by shibupanda** [comment]
Error:
====
2019-03-25 15:15:38:566 - info: [debug] [MJSONWP] java.lang.IllegalArgumentException: Unknown id: com.sec.android.inputmethod/.SamsungKeypad
2019-03-25 15:15:38:566 - info: [debug] [MJSONWP] 	at com.android.server.InputMethodManagerService.setInputMethodEnabledLocked(InputMethodManagerService.java:6096)
2019-03-25 15:15:38:567 - info: [debug] [MJSONWP] 	at com.android.server.InputMethodManagerService.handleShellCommandEnableDisableInputMethod(InputMethodManagerService.java:8241)
2019-03-25 15:15:38:569 - info: [debug] [MJSONWP] 	at com.android.server.InputMethodManagerService.access$4800(InputMethodManagerService.java:274)
2019-03-25 15:15:38:569 - info: [debug] [MJSONWP] 	at com.android.server.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:8032)
2019-03-25 15:15:38:569 - info: [debug] [MJSONWP] 	at android.os.ShellCommand.exec(ShellCommand.java:103)
2019-03-25 15:15:38:569 - info: [debug] [MJSONWP] 	at com.android.server.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:7998)
2019-03-25 15:15:38:570 - info: [debug] [MJSONWP] 	at android.os.Binder.shellCommand(Binder.java:642)
2019-03-25 15:15:38:570 - info: [debug] [MJSONWP] 	at android.os.Binder.onTransact(Binder.java:540)
2019-03-25 15:15:38:570 - info: [debug] [MJSONWP] 	at com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:622)
2019-03-25 15:15:38:570 - info: [debug] [MJSONWP] 	at com.android.server.InputMethodManagerService.onTransact(InputMethodManagerService.java:2386)
2019-03-25 15:15:38:571 - info: [debug] [MJSONWP] 	at android.os.Binder.execTransact(Binder.java:739)'; Code: '255'
2019-03-25 15:15:38:571 - info: [debug] [MJSONWP]     at ADB.execFunc$ (.npm-packages/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:327:13)
2019-03-25 15:15:38:571 - info: [debug] [MJSONWP]     at tryCatch (.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2019-03-25 15:15:38:571 - info: [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2019-03-25 15:15:38:572 - info: [debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2019-03-25 15:15:38:573 - info: [debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke (.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2019-03-25 15:15:38:573 - info: [debug] [MJSONWP]     at <anonymous>

**Comment by imurchie** [comment]
Please provide the _full_ Appium server logs (as a link to a [gist](https://gist.github.com)). This is not enough information to go on.

**Comment by shibupanda** [comment]
@imurchie Please find the complete logs in the below link.
https://gist.github.com/shibupanda/14fcc5425fcc43430a75ab8c21fd3215

**Comment by KazuCocoa** [comment]
Thanks. Can you give us below logs in additon?

1. Can you give us logcat when you run `android/platform-tools/adb -P 5037 -s ce10171abcc1c930037e shell ime enable io.appium.android.ime/.UnicodeIME`?
2. Can you give a log of `adb shell ime list -s`?

**Comment by shibupanda** [comment]
@KazuCocoa 
1. Can you give us logcat when you run android/platform-tools/adb -P 5037 -s ce10171abcc1c930037e shell ime enable io.appium.android.ime/.UnicodeIME?
https://gist.github.com/shibupanda/90199765bbd65ced10068b4c20cdb17d

adb -P 5037 -s ce10171abcc1c930037e shell ime enable io.appium.android.ime/.UnicodeIME
Input method io.appium.android.ime/.UnicodeIME: already enabled

2. Can you give a log of adb shell ime list -s?
com.google.android.googlequicksearchbox/com.google.android.voicesearch.ime.VoiceInputMethodService
com.sec.android.inputmethod/.SamsungKeypad
io.appium.android.ime/.UnicodeIME

Like to add one more point i.e it only reproduce on v9.0 devices(Samsung, Oneplus)

**Comment by KazuCocoa** [comment]
Figured out.
`adb install` command faield to install the setting app. Then, the error happens.
I'll improve the installation logic.

**Comment by shibupanda** [comment]
I have found the same before raising the issue and I did some setting so that it is not going to uninstall setting app forever. Then also I faced the same error.
@KazuCocoa whether we are not checking the status of setting app before installing?

**Comment by KazuCocoa** [comment]
I guess raising error was missed in some refactoring since the code was updated over 2 years ago.
Just the errror handling showed a warning message in log.

I've changed to throw error after retry once in https://github.com/appium/appium-android-driver/pull/525 since the setting is necessary for android testing.

**Comment by shibupanda** [comment]
@KazuCocoa Agree.
I am attaching one more log there the status of setting app is installed still it is throwing the error.
One more observation I want to put here.
If I initialized the driver twice I got this very first time only retry may help us here.

**Comment by KazuCocoa** [comment]
Could you update to the latest Appium? (1.10.0 at least)
Over 1.10.0, the IME app has been merged to the settings app. I guess in your case, IME helper app did not installed while the setting app had been installed.

**Comment by shibupanda** [comment]
Let me install 1.10.0 and I will come to you in case of any issues.

**Comment by ArtificialZeng** [comment]
> Please provide the _full_ Appium server logs (as a link to a [gist](https://gist.github.com)). This is not enough information to go on.

[Appium] Welcome to Appium v1.22.3
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] Request idempotency key: 89e3ddb6-f3b7-4a4d-942d-473fa195cf62
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android","appium:plathformVersion":"8","appium:deviceName":"test0106","appium:appPackage":"com.alpha.lagouapk","appium:appActivity":".HelloActivity","appium:noReset":true,"appium:newCommandTimeout":6000,"appium:automationName":"UiAutomator1","appium:unicodeKeyboard":true,"appium:resetKeyboard":true}}}
[W3C] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android","appium:plathformVersion":"8","appium:deviceName":"test0106","appium:appPackage":"com.alpha.lagouapk","appium:appActivity":".HelloActivity","appium:noReset":true,"appium:newCommandTimeout":6000,"appium:automationName":"UiAutomator1","appium:unicodeKeyboard":true,"appium:resetKeyboard":true}}]
[BaseDriver] Event 'newSessionRequested' logged at 1661937972560 (17:26:12 GMT+0800 (中国标准时间))
[Appium] Appium v1.22.3 creating new AndroidDriver (v4.51.0) session
[Appium] Applying relaxed security to 'AndroidDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "Android",
[BaseDriver]     "appium:plathformVersion": "8",
[BaseDriver]     "appium:deviceName": "test0106",
[BaseDriver]     "appium:appPackage": "com.alpha.lagouapk",
[BaseDriver]     "appium:appActivity": ".HelloActivity",
[BaseDriver]     "appium:noReset": true,
[BaseDriver]     "appium:newCommandTimeout": 6000,
[BaseDriver]     "appium:automationName": "UiAutomator1",
[BaseDriver]     "appium:unicodeKeyboard": true,
[BaseDriver]     "appium:resetKeyboard": true
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   plathformVersion
[BaseDriver] Session created with session id: fb77c155-6d0a-4613-8435-b27a3a00989d
[ADB] Found 1 'build-tools' folders under 'G:\A_IDE\Android\Sdk' (newest first):
[ADB]     G:/A_IDE/Android/Sdk/build-tools/33.0.0
[ADB] Using 'adb.exe' from 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"55f8c28e","state":"device"}]
[AndroidDriver] Using device: 55f8c28e
[ADB] Using 'adb.exe' from 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to 55f8c28e
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 31
[ADB] Getting device platform version
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 12
[ADB] Device API level: 31
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.alpha.lagouapk directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell pm list packages com.alpha.lagouapk'
[AndroidDriver] Starting Android session
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e wait-for-device'
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.4.0' >= '3.4.0')
[ADB] There is no need to install/upgrade 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell 'pgrep --help; echo $?''
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell appops set io.appium.settings android:mock_location allow'
[AndroidDriver] Unable to set mock location for app 'io.appium.settings': Error executing adbExec. Original error: 'Command 'G:\\A_IDE\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 55f8c28e shell appops set io.appium.settings android\:mock_location allow' exited with code 255'; Command output: 
[AndroidDriver] Exception occurred while executing 'set':
[AndroidDriver] java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
[AndroidDriver] 	at android.app.ContextImpl.enforce(ContextImpl.java:2186)
[AndroidDriver] 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:2195)
[AndroidDriver] 	at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2560)
[AndroidDriver] 	at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2829)
[AndroidDriver] 	at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2824)
[AndroidDriver] 	at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5565)
[AndroidDriver] 	at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:5334)
[AndroidDriver] 	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
[AndroidDriver] 	at android.os.ShellCommand.exec(ShellCommand.java:38)
[AndroidDriver] 	at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5506)
[AndroidDriver] 	at android.os.Binder.shellCommand(Binder.java:970)
[AndroidDriver] 	at android.os.Binder.onTransact(Binder.java:854)
[AndroidDriver] 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1198)
[AndroidDriver] 	at com.android.server.appop.OplusAppOpsService.onTransact(OplusAppOpsService.java:38)
[AndroidDriver] 	at android.os.Binder.execTransactInternal(Binder.java:1226)
[AndroidDriver] 	at android.os.Binder.execTransact(Binder.java:1163)
[AndroidDriver] 
[Logcat] Starting logs capture with command: G:\\A_IDE\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 55f8c28e logcat -v threadtime
[AndroidDriver] Enabling Unicode keyboard support
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell settings get secure default_input_method'
[AndroidDriver] Unsetting previous IME com.baidu.input_oppo/.ImeService
[AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell ime enable io.appium.settings/.UnicodeIME'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[Logcat] Stopping logcat capture
[ADB] Running 'G:\A_IDE\Android\Sdk\platform-tools\adb.exe -P 5037 -s 55f8c28e shell am force-stop io.appium.unlock'
[BaseDriver] Event 'newSessionStarted' logged at 1661937983082 (17:26:23 GMT+0800 (中国标准时间))
[W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'G:\\A_IDE\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 55f8c28e shell ime enable io.appium.settings/.UnicodeIME' exited with code 255'; Command output: 
[W3C] Exception occurred while executing 'ime':
[W3C] java.lang.SecurityException: uid 2000 does not have android.permission.WRITE_SECURE_SETTINGS.
[W3C] 	at android.app.ContextImpl.enforce(ContextImpl.java:2186)
[W3C] 	at android.app.ContextImpl.enforceCallingPermission(ContextImpl.java:2204)
[W3C] 	at com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl.lambda$onCommand$0$InputMethodManagerService$ShellCommandImpl(InputMethodManagerService.java:5556)
[W3C] 	at com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl$$ExternalSyntheticLambda0.accept(Unknown Source:4)
[W3C] 	at java.util.Arrays$ArrayList.forEach(Arrays.java:3805)
[W3C] 	at com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:5556)
[W3C] 	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
[W3C] 	at android.os.ShellCommand.exec(ShellCommand.java:38)
[W3C] 	at com.android.server.inputmethod.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:5530)
[W3C] 	at android.os.Binder.shellCommand(Binder.java:970)
[W3C] 	at android.os.Binder.onTransact(Binder.java:854)
[W3C] 	at com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:533)
[W3C] 	at com.android.server.inputmethod.InputMethodManagerService.onTransact(InputMethodManagerService.java:1804)
[W3C] 	at com.android.server.inputmethod.OplusInputMethodManagerService.onTransact(OplusInputMethodManagerService.java:196)
[W3C] 	at android.os.Binder.execTransactInternal(Binder.java:1226)
[W3C] 	at android.os.Binder.execTransact(Binder.java:1163)
[W3C] 
[W3C] Error: Command 'G:\\A_IDE\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 55f8c28e shell ime enable io.appium.settings/.UnicodeIME' exited with code 255
[W3C]     at ChildProcess. (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[W3C]     at ChildProcess.emit (events.js:310:20)
[W3C]     at maybeClose (internal/child_process.js:1021:16)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[HTTP] <-- POST /wd/hub/session 500 10524 ms - 4291
[HTTP]
